---
title: "Cecilie_071025"
format: html
---

# AU - procedurer

## Ferie

Ferie er bøvlet at registrere. Hvis man ikke indberetter ferie, bliver den bare udbetalt på de mest gængse ferietidspunkter (efterårsferie, juleferie, etc.)

## Sygefravær

Der registreres sygefravær eller barns sygedag, hvis det trækker ud. Dette sker til Annelli

## PhD plan i MyPHD

Skal lavet som en del af 6-måneders evaluering. Lav reminder en måned inden. Man laver en status for projektet. Desuden skal der være en bekræftelse af mit udlandsophold. 

Der kommer ligeledes en halvvejsevaluering. 

## Journal club

Man skal deltage i en journal club i løbet af sin PhD. 
- epidemyologi
- kvalitativt
- komplekse interventioner (Randi Nielsen)

## Undervisning

Man ksla have 150 undervisningstimer
Der mangler typisk undervisere til basale forelæsninger til sygdomslære på institut for folkesundhed. 
Linda: Står for undervsining i folkesundhedsvidenskab. Både cases og forlæsninger. 

## Valgfag

Lav et dokument så jeg hurtigt kan udvælge hvilke fag jeg skal have hvornår. 
Ramme ca. 15 ud af 30 ects. 
