---
title: "Vejlederm칮de_Annelli_220126"
format:
  pdf:
    pdf-engine: lualatex
    fontsize: 10pt
    linestretch: 1.2
    geometry:
      - margin=2.5cm
    tbl-cap-location: top
    number-sections: false
    toc: false
    keep-tex: true
execute:
  echo: false
  warning: false
  message: false
header-includes:
  - \usepackage{microtype}
  - \usepackage{ragged2e}
  - \usepackage{tabularx}
  - \usepackage{longtable}
  - \usepackage{booktabs}
  - \usepackage{array}
  - \usepackage{pdflscape}
  - \usepackage{setspace}
  - \usepackage{float}
  - \setlength{\emergencystretch}{3em}
  - \renewcommand{\arraystretch}{1.2}
---

# Dagsorden

## Tid og sted

**Tid:** 30 min\
**Sted:** Annellis kontor

## 游리 Intention

Form친let med m칮det er at give en status p친 ph.d.-projektet, fondsans칮gningerne og dr칮fte det Cardiovascular Programme og f칝lles vejlederm칮de.

## 游릭 Desired Outcome

Ved m칮dets afslutning har vi:

\[X\] **En f칝lles opdateret forst친else af projektets status**\
- *Kurser:* 
    How to manage you phd project
    Time management
    Developing complex interventons
    Biostat 1.
    Phd day
    Welcome to the phd study
    
- Oprettet p친 Danmarks Statistik -> analyser til paper 3

- Afpr칮vet interviewguide og f칮rste interview til paper 2

- Mangler fortsat svar fra SDU vedr칮rende DBA deling af acc. data til Paper 1

\[X\] **Trygfonden\**
- Jeg har orienteret mig i Trygfondens fokus og det synes relevant at s칮ge. 
- Vi kigger p친 budgettet og bliver enige om hvor meget vi skal s칮ge hos Trygfonden

*Beslutning*: Efter at have genneml칝st opslaget, st친r det klart at trygfonden ikke st칮tter rehabiltering som kun foreg친r i sundhedsv칝snet. Vi dropper derfor trygfonden. Jeg holder 칮je med DFF klinisk forskning og DFF tematiske opslag. 

*Fra sidste m칮de:*
Ans칮gning til Region Midtjylland er blevet sorteret fra inden den er blevet l칝st. Derfor s칮ges den ikke igen. Vi aftaler at jeg nedprioriterer fondsans칮gningerne for en tid. Der skal s칮ges 3 fonde det kommende 친r: - Trygfonden (marts) - Jeg ringer og forh칮rer mig om projektet flugter med deres fokus i 친r - DFF klinisk forskning (start juni) - Jeg holder l칮bende 칮je med call. Obs p친 minimum bel칮b p친 ca. 2 millioner. Vi m친 finde flere poster at skrive p친. - Helsefonden (august) - 300.000 kr.

\[X\] **Truffet beslutning om Cardiovascular Network**\
- Jeg er i tvivl om hvad jeg f친r ud af dette netv칝rk. Det virker langt fra det jeg arbejder med. 
- Jeg vil gerne prioritere andre Journal Clubs og valgfag. 
- Er der noget jeg overser?

*Beslutning:* Jeg afskriver mig Cardiovascular Network og prioriterer kurser og jounal clubs som padser bedre til mit forskningsfelt.  

\[X\] **Dr칮fte det f칝lles vejlederm칮de d. 19 februar**\
- Jeg har ikke s칝rlig meget at opdatere p친 - udskyde det?
- Eventuelt en anden tilgang?

*Beslutning* Vi rykker m칮det til slut april. Emner kan v칝re analyseplan eller forel칮bige resultater p친 artikel 3. Eventuel publicering af analyseplan. Desuden skal de andre vejederes perspektiv p친 analyseplanen for studie 1 og der skal tages stilling til om analyseplanen skal p친 som amendment til clinicaltrial.gov.
