---
title: "Cecilie_071025"
format: html
---

# AU – Procedurer og Praktisk Information

## Ferie

Registrering af ferie kan være lidt bøvlet. Hvis man ikke aktivt indberetter sin ferie, bliver den automatisk udbetalt på de mest almindelige ferietidspunkter (fx efterårsferie og juleferie). 

## Sygefravær

Sygefravær eller barns sygedag registreres, hvis fraværet trækker ud. Dette meldes til Annelli.

## PhD-plan i MyPhD

PhD-planen skal udarbejdes i forbindelse med 6-måneders evalueringen. Det er en god idé at sætte en reminder en måned i forvejen.  
I planen skal der både laves en status på projektet og bekræftes plan for udlandsopholdet.  

Derudover skal der gennemføres en halvvejsevaluering undervejs i forløbet.

## Journal Club

I løbet af PhD-forløbet skal man deltage i mindst én journal club. Mulige journal clubs inkluderer:

- Epidemiologi  
- Kvalitative metoder  
- Komplekse interventioner (v. Randi Nielsen)

## Undervisning

Der skal i alt indgå 150 undervisningstimer i løbet af PhD’en.  
Der mangler typisk undervisere til basale forelæsninger i sygdomslære på Institut for Folkesundhed.  

**Linda** står for undervisning i folkesundhedsvidenskab – både cases og forelæsninger. Se tilsendte mails. 

## Valgfag

Det er en god idé at lave et dokument, der giver et hurtigt overblik over, hvilke fag jeg ønsker at tage, og hvornår.  

